config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  resources :gerentes
  resources :funcionarios
  resources :vendas
  resources :item_pedidos
  resources :produtos
  resources :estoques
  resources :estoque_produtos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estoque.rb
class Estoque < ActiveRecord::Base
  has_many :estoque_produtos, dependent: :destroy
  has_many :item_pedidos, dependent: :destroy
  validates :nome, presence: true
end

app/models/estoque_produto.rb
class EstoqueProduto < ActiveRecord::Base
  belongs_to :produto
  belongs_to :estoque
  validates :produto_id, presence: true,
                         uniqueness: {scope: :estoque_id, message: 'O estoque selecionado já contém este produto'}
  validates :estoque_id, presence: true
  validates :quantidade, presence: true

end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
end

app/models/gerente.rb
class Gerente < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/item_pedido.rb
class ItemPedido < ActiveRecord::Base
  belongs_to :produto
  belongs_to :venda
  belongs_to :estoque
  validates :venda_id, presence: true
  validates :produto_id, presence: true
  validates :quantidade, presence: true
  validates :estoque_id, presence: true

  def destroy
    #acha a venda do item_pedido
    @venda = Venda.find(venda_id)
    #atualiza valor da venda
    @venda.update(valor_total: @venda.valor_total - quantidade * produto.valor)
    #atualiza quantidade do estoque
    @estoque_produto = EstoqueProduto.find_by(produto_id: produto_id,
                                              estoque_id: estoque_id)
    @estoque_produto.update(quantidade: @estoque_produto.quantidade + quantidade)
    #destroy ItemPedido
    super
  end

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  has_many :item_pedidos, dependent: :destroy
  has_many :estoque_produtos, dependent: :destroy
  validates :nome, presence: true
  validates :valor, presence: true

end

app/models/venda.rb
class Venda < ActiveRecord::Base
  has_many :item_pedidos



  def destroy
    item_pedidos.each do |i|
      i.destroy
    end
    super
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/estoque_produtos_controller.rb
class  EstoqueProdutosController < ApplicationController
  def index
    @estoque_produto = EstoqueProduto.all
  end

  def new
    @estoque_produto = EstoqueProduto.new(:estoque_id => params[:estoque_id])
  end

  def create
   # @estoque = Estoque.find(params[:estoque_id])
    @estoque_produto = EstoqueProduto.new(estoque_produto_params)
    if @estoque_produto.save
      redirect_to @estoque_produto
    else
      render 'new'
    end
  end

  def show
    @estoque_produto = EstoqueProduto.find(params[:id])
  end
  private
  def estoque_produto_params
    params.require(:estoque_produto).permit(:estoque_id, :produto_id,:quantidade)
  end
end

app/controllers/estoques_controller.rb
class EstoquesController < ApplicationController
  def index
    @estoque = Estoque.all
  end

  def new
    @estoque = Estoque.new
  end

  def create
    @estoque = Estoque.new(estoque_params)
    if @estoque.save
      redirect_to @estoque
    else
      render 'new'
    end
  end

  def show
    @estoque = Estoque.find(params[:id])
  end

  def find_all_from_estoque_id(id)
    EstoqueProduto.find_by_estoque_id(id)
  end

  private
  def estoque_params
      params.require(:estoque).permit(:nome)
  end


end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  def index
    @vendas = Venda.all
  end
end

app/controllers/gerentes_controller.rb
class GerentesController < ApplicationController
  def index
    @gerente = Gerente.all
  end

  def new
    @gerente = Gerente.new
  end

  def create
    @gerente = Gerente.new
    if @gerente.save
      redirect_to @gerente
    else
      render 'new'
    end
  end

  def show
    @gerente = Gerente.find(params[:id])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/item_pedidos_controller.rb
class ItemPedidosController < ApplicationController
  def index
  end
  def new()
    @item_pedido = ItemPedido.new
    @item_pedido.venda_id=params[:id_venda]
  end

  def create
    @estoque_produto =EstoqueProduto.find_by(:produto_id => item_pedido_params[:produto_id],:estoque_id => item_pedido_params[:estoque_id])
    unless @estoque_produto.nil? #se o produto existe
      if item_pedido_params[:quantidade].to_i <= @estoque_produto.quantidade #se a quantidade está disponviel
        @item_pedido = ItemPedido.new(item_pedido_params)
        if @item_pedido.save
          #remove quantidade do estoque
          @estoque_produto.update(quantidade: (@estoque_produto.quantidade - item_pedido_params[:quantidade].to_i) )
          #adiciona valor na venda
          @venda = Venda.find_by(:id => item_pedido_params[:venda_id])
          @venda.update(valor_total: @venda.valor_total + @item_pedido.quantidade * @item_pedido.produto.valor)
          redirect_to @venda
        else
          render 'new'
        end
      else #se a quantidade não está disponível
        puts "error"
      end
    else #se o produto não existe
      puts "error"
    end

  end

  def destroy
    @item_pedido = ItemPedido.find(params[:id])
    @item_pedido.destroy
    redirect_to venda_path(params[:venda_id])
  end


  private
  def item_pedido_params
    params.require(:item_pedido).permit(:estoque_id, :produto_id, :quantidade, :venda_id)
  end


end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def index
    @produto = Produto.all
  end

  def new
    @produto = Produto.new
  end

  def create
    @produto = Produto.new(produto_params)
    if @produto.save
      redirect_to @produto
    else
      render 'new'
    end
  end

  def show
    @produto = Produto.find(params[:id])
  end

  def edit
    @produto = Produto.find(params[:id])
  end

  def update
    @produto = Produto.find(params[:id])
    if @produto.update(produto_params)
      redirect_to @produto
    else
      render 'new'
    end
  end

  private
  def produto_params
    params.require(:produto).permit(:nome, :valor)
  end
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  def index
    @vendas = Venda.all
  end

  def new
    @venda = Venda.new

    create
  end

  def create
    @venda = Venda.new
    @venda.valor_total = 0
    if @venda.save
      redirect_to @venda
    else
      render 'new'
    end
  end

  def show
    @venda = Venda.find(params[:id])
  end

  def destroy
    @venda = Venda.find(params[:id])
    @venda.destroy
    redirect_to funcionarios_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/estoque_produtos/_form.html.erb
<%= form_for @estoque_produto do |f| %>

    <% if @estoque_produto.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@estoque_produto.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @estoque_produto.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :estoque_id %>
      <%= f.collection_select(:estoque_id, Estoque.all, :id, :nome, {disabled: 'Curitiba'}) %>
    </p>
    <p>
      <%= f.label :produto_id %>
      <%= f.collection_select(:produto_id, Produto.all, :id, :nome) %>
    </p>
    <p>
      <%= f.label :quantidade %><br>
      <%= f.number_field :quantidade, min: 0 %>
    </p>

    <p>
      <%= f.submit "Adicionar" %>
    </p>

<% end %><br>
<%= link_to "Voltar",  :back %>

app/views/estoque_produtos/index.html.erb
<h1>Estoques</h1>
<br>
<% @estoque_produto.each do |estoque_produto| %>
    Nome: <%= estoque_produto.produto_id %>
    <br>
<% end %>
<br>
<%= link_to "Novo Estoque",  new_estoque_path %>

app/views/estoque_produtos/new.html.erb
<%= render 'form' %>

app/views/estoque_produtos/show.html.erb
<p>
  Nome: <%= @estoque_produto.produto.nome %><br>
  Quantidade: <%= @estoque_produto.quantidade %>
</p>

<%= link_to "Voltar",  :back %>

app/views/estoques/_form.html.erb
<%= form_for @estoque do |f| %>

    <% if @estoque.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@estoque.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @estoque.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :nome %><br>
      <%= f.text_field :nome %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/estoques/index.html.erb
<h2>Estoque</h2>
<br>
<% @estoque.each do |estoque| %>
  Nome: <%= estoque.nome %> <%= link_to " Mostrar",  estoque_path(estoque) %>
<br>
<% end %>
<br>
<%= link_to "Novo Estoque ",  new_estoque_path %><br>
<%= link_to "Adicionar Produto",  new_estoque_produto_path %><br>
<%= link_to "Voltar",  :back %>

app/views/estoques/new.html.erb
<%= render 'form' %><br>
<%= link_to "Voltar",  :back %>

app/views/estoques/show.html.erb
<h1><%= @estoque.nome %></h1>

<% @estoque.estoque_produtos.includes(:produto).each do |e| %>
  <p>
    Nome: <%= e.produto.nome %><br>
    Quantidade: <%= e.quantidade %>
  </p>
<% end %>
<br>
<%= link_to "Adicionar Produto", new_estoque_produto_path(:estoque_id => @estoque.id) %><br>
<%= link_to "Voltar",  :back %>

app/views/funcionarios/index.html.erb
<h2>Vendas</h2>

<% @vendas.each do |v| %>
    ID Venda: <%= v.id %> <%= link_to "Mostrar", venda_path(v) %> <%= link_to "Remover", venda_path(v),method: :delete, data: { confirm: "Confirmar remoção" } %><br>
    Total <%= v.valor_total %>
    <br><br>
    <% end %>

<%= link_to "Nova Venda",  new_venda_path %>

<%= link_to "Voltar",  :back %>

app/views/gerentes/index.html.erb
<h2>Gerente</h2>
<%= link_to "Produtos",  produtos_path %><br>
<%= link_to "Estoques",  estoques_path %>

app/views/item_pedidos/_form.html.erb
<%= form_for @item_pedido do |f| %>
    <% if @item_pedido.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@item_pedido.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @item_pedido.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :venda_id %><br>
      <%= f.text_field :venda_id, :disabled => true %>
      <%= f.hidden_field :venda_id %>
    </p>
    <p>
      <%= f.label :produto_id %><br>
      <%= f.text_field :produto_id %>
    </p>
    <p>
      <%= f.label :quantidade %><br>
      <%= f.number_field :quantidade %>
    </p>
    <p>
    <%= f.label :estoque_id %><br>
    <%= f.collection_select(:estoque_id, Estoque.all, :id, :nome) %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/item_pedidos/new.html.erb
<%= render 'form' %><br>
<%= link_to "Voltar",  vendas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mercado" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href= "/" >Mercado</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Gerente", gerentes_path  %></li>
            <li><%= link_to "Funcionario", funcionarios_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!--<div class="col-lg-3">-->
          <!--<div class="well sidebar-nav">-->
            <!--<h3>Sidebar</h3>-->
            <!--<ul class="nav nav-list">-->
              <!--<li class="nav-header">Sidebar</li>-->
              <!--<li><%= link_to "Link1", "/path1"  %></li>-->
              <!--<li><%= link_to "Link2", "/path2"  %></li>-->
              <!--<li><%= link_to "Link3", "/path3"  %></li>-->
            <!--</ul>-->
          <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
        <!--</div>&lt;!&ndash;/span&ndash;&gt;-->
      </div><!--/row-->

      <footer>
        <br><br><br>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/produtos/_form.html.erb
<%= form_for @produto do |f| %>

    <% if @produto.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @produto.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :nome %><br>
      <%= f.text_field :nome %>
    </p>

    <p>
      <%= f.label :valor %><br>
      <%= f.number_field :valor, min: 0, step: 0.01 %>
    </p>

    <p>
      <%= f.submit "Adicionar" %>
    </p>

<% end %>

app/views/produtos/edit.html.erb
<h1>Modificar Produto</h1>
<%= render 'form' %><br>
<%= link_to "Voltar",  :back %>

app/views/produtos/index.html.erb
<% @produto.each do |p|  %>
<tr>
  <td>ID: <%= p.id %></td><br>
  <td>Nome: <%= p.nome %> <%= link_to " Editar", edit_produto_path(p)%> </td><br>
  <td>Valor: <%= p.valor %></td>
</tr>
<br><br>
<%end%>
<br>
<%= link_to "Novo Produto",  new_produto_path %> <br>
<%= link_to "Voltar",  :back %>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>
<%= render 'form' %>
<%= link_to "Voltar",  :back %>

app/views/produtos/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @produto.valor %>
</p>

<br>
<%= link_to "Modificar Produto",  edit_produto_path(@produto) %><br>
<%= link_to "Voltar",  produtos_path %>

app/views/vendas/_form.html.erb
<%= form_for @venda do |f| %>

    <% if @venda.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@venda.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @venda.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :nome %><br>
      <%= f.text_field :nome %>
    </p>

    <p>
      <%= f.label :valor %><br>
      <%= f.number_field :valor, min: 0, step: 0.01 %>
    </p>

    <p>
      <%= f.submit "Adicionar" %>
    </p>

<% end %>

app/views/vendas/index.html.erb
<% @vendas.each do |v| %>
    ID: <%= v.id %> <%= link_to "Mostrar", venda_path(v) %>
    <%= link_to "Remover", venda_path(v), method: :delete, data: { confirm: 'Confirmar Remoção' } %><br>
    Total <%= v.valor_total %>
    <br><br>
<% end %>

app/views/vendas/show.html.erb
<p>
  <strong>ID:</strong>
  <%= @venda.id %>
</p>

<% @venda.item_pedidos.each do |i| %>
    Produto: <%= i.produto.nome %> <%= link_to "Remover", item_pedido_path(i,:venda_id => @venda.id), method: :delete, data: { confirm: 'Confirmar Remoção' } %><br>
    Quantidade: <%= i.quantidade %><br>
    <br>
<% end %>

<p>
  <strong>Total:</strong>
  <%= @venda.valor_total %>
</p>
<%= link_to "Adicionar Item",  :controller => "item_pedidos",
                               :action => "new",
                               :id_venda => @venda.id %>
<%= link_to "Voltar",  :back %>